### ISSUE TITLE
Disable touch ID

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-webauthn-authenticator#17]
**Background**
Touch ID seems to be an 'attestation' that's provided by default with the WebAuthn API.

Touch ID isn't something that we're planning on providing as part of the initial project. To avoid additional thought to go into UX flows for this, we should disable it.

**AC**
- When registering with the WebAuthn method, by CWP-default, users should only asked to be registered with what we understand a security key to manage.

**Comment by robbieaverill** [comment]
We could make the "disable touch ID" configurable, in which we disable it by default, in case people actually want to use it for their projects

**Comment by ScopeyNZ** [comment]
Found the relevant part of the API:

https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredentialCreationOptions/authenticatorSelection

**Comment by chillu** [comment]
Yeah please make this configurable, it's a great marketing feature - particularly mentioning FaceID and SilverStripe in the same sentence. @clarkepaul What are the concerns in terms of UX on this? My concerns are more around organisational rules: A certain org might require their staff to use hardware keys, and while they provide work iPhones, they don't manage them centrally (e.g. enforcing a strong passcode). So their CISO isn't comfortable replacing a (known safe) hardware key with a potentially weaker TouchID or FaceID based on individual staff choice. It's all a bit contrived, but I can see the use case.

In the end, I want to make sure we don't block this important and increasing use case (built-in device MFA) because we designed an icon as a "key" rather than something more abstract.

**Comment by robbieaverill** [comment]
Yeah it's probably more that we don't want to support single device factors by default (configurable) since you might lock your MFA settings to your phone by accident.

**Comment by ScopeyNZ** [comment]
> Yeah it's probably more that we don't want to support single device factors by default (configurable) since you might lock your MFA settings to your phone by accident.

I'm of the opinion that we can't make it configurable until we support multiple device registrations in one method registration. It's a little more work. It requires different UI though - and we'd need to do some weird stuff to allow management in the CMS for just that method. Maybe we need to do a similar pattern that is done in elemental for block actions?

**Comment by robbieaverill** [comment]
Or allow the same Method to be registered more than once, e.g. 3x TOTPs, 2x YubiKeys and 1x fingerprint

**Comment by clarkepaul** [comment]
Apparently, there's about a 1 in 50,000 chance someone else's fingerprint could be mistaken for yours, and a 1 in 100,000 your face could be mistaken (Apple stats). I personally don't have too many concerns as this field progresses so fast that it is already been proven to be successful, every method has its downsides which would need to be known/addressed by people who implement it. As mentioned above the UI doesn't fit this experience and would need to be modified is the caveat. I'm all for multiple methods of the same type to be registered but I don't think its high priority. Getting the status quo out is going to be enough of a challenge. I don't think we've backed ourselves into any corner in terms of how we've designed it so far.

**Comment by chillu** [comment]
> I'm of the opinion that we can't make it configurable until we support multiple device registrations in one method registration. 

People can loose phones, they can loose hardware tokens. We already have reset mechanisms in place. I don't really see a difference here, and the discussion for supporting multiple methods (e.g. Yubikey plus TouchID) seems like a distraction for this ticket? In my mind it's more around organisational preference for a *single* hardware token, as outlined above. 

@ScopeyNZ Maybe I'm misunderstanding you - why do you think "allowing platform-specific device authenticators like TouchID" is coupled with "allowing multiple device registrations"?

**Comment by ScopeyNZ** [comment]
Because you have to register each device individually. Your fingerprint on your phone is _not_ the same as your fingerprint on your MacBook Pro. The WebAuthn library caters for this - it provides an interface that is tasked with fetching specific credentials from a collection that belongs to a single user.

I think "allowing platform-specific device authenticators like TouchID" is coupled with "allowing multiple device registrations" because it's a pretty awful user experience if you can only have one authorised device at a time with WebAuthn.

> Allow the same Method to be registered more than once, e.g. 3x TOTPs, 2x YubiKeys and 1x fingerprint (3x WebAuthn RegisteredMethods)

This becomes too hard in the case of TOTP I think. You would have to name your registration so you know what one to pick when you log in.

**Comment by newleeland** [comment]
If we were to allow TouchID, it shouldn't be configured it in the Security key (webauthn) user flow. We could consider disabling TouchID from the WebAuthn user flow and have it as another method called TouchID? This would require more UI and content I'd imagine. Even though it would be nice selling point, it seems more like a nice to have, as it would only benefit a limited number of users, and because of the limitation @ScopeyNZ raised, that a fingerprint registered on a device cannot be reused on another device.

**Comment by robbieaverill** [comment]
@newleeland we're mostly discussing the backend implementation of how we handle the WebAuthn protocol here, rather than the UI we've built around it. Agreed, promoting a single authenticator factor (security key) out of whatever WebAuthn supports is limiting, and it will probably require re-work in future if biometric validation were a more standard use case for the module, but I agree with @chillu that disabling touch ID now because the UI doesn't indicate that you can use it is the wrong choice to make. The more valid concern is around the fact that fingerprints are tied to a single device, which to me is more why we'd want to disable it, rather than the UI.

**Comment by robbieaverill** [comment]
Relevant backend docs for this: https://github.com/web-auth/webauthn-framework/blob/v1.2/doc/webauthn/PublicKeyCredentialCreation.md#authenticator-selection-criteria

**Comment by robbieaverill** [comment]
PR here: https://github.com/silverstripe/silverstripe-webauthn-authenticator/pull/23
